version: 0.0.1.{build}

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd

test: off

artifacts:
- path: build/*.nupkg
  name: NugetPackage

deploy:
- provider: NuGet
  api_key:
    secure: sQzzieUQGkTU0CvzXLcv5Wph6K7h3T+8teovqwa/Dzk1p9WhpmuUHiRxd3U0YhqO
  artifact: 'NuGetPackage'
  on:
    branch: release